name: filen_dart
description: Filen.io CLI client in Dart (unofficial)
version: 0.0.2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  http: ^1.1.0
  pointycastle: ^3.7.3
  hex: ^0.2.0
  path: ^1.8.3
  convert: ^3.1.1
  glob: ^2.1.2

dev_dependencies:
  lints: ^2.1.0